# Generated by Django 4.2.3 on 2023-07-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Buyer", "Buyer"),
                            ("Seller", "Seller"),
                            ("Admin", "Admin"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Buyer", "Buyer"),
                            ("Seller", "Seller"),
                            ("Admin", "Admin"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
