# Generated by Django 4.2.3 on 2023-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
