# Generated by Django 4.2.3 on 2023-07-12 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_account_groups_account_is_active_account_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="account",
            name="is_staff",
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="password",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=128,
                verbose_name="password",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
