# Generated by Django 4.2.3 on 2023-07-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0005_remove_account_is_active_remove_account_is_staff_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
